export const itemsRome: any[] = [
  {"id":1, "monumentName": "Colosseo", "img": "assets/img/rome/colosseo.jpg", "descrizione": "Celebre arena dei gladiatori romani", "rating": 5, "votanti": "233.763"},
  {"id":2, "monumentName": "Basilica di San Pietro", "img": "assets/img/rome/vaticano.jpg", "descrizione": "Più grande basilica del mondo", "rating": 5, "votanti": "111.675"},
  {"id":3, "monumentName": "Fori Imperiali", "img": "assets/img/rome/fori.jpg", "descrizione": "Scavi nel cuore del centro Romano", "rating": 5, "votanti": "99.744"},
  {"id":4, "monumentName": "Fontana di Trevi", "img": "assets/img/rome/trevi.png", "descrizione": "Celebre fontana del '700", "rating": 5, "votanti": "245.750"},
  {"id":5, "monumentName": "Pantheon", "img": "assets/img/rome/pantheon.jpeg", "descrizione": "Celebre chiesa romana", "rating": 5, "votanti": "135.680"},
  {"id":6, "monumentName": "Altare della Patria", "img": "assets/img/rome/patria.jpg", "descrizione": "Monumento memoriale", "rating": 5, "votanti": "28.444"}
]

export const itemsParigi: any[] = [
  {"id":7, "monumentName": "Torre Eiffel", "img": "assets/img/parigi/eiffel.jpg", "descrizione": "Famosa torre dell'800 alta 324m", "rating": 5, "votanti": "223.116"},
  {"id":8, "monumentName": "Museo del Louvre", "img": "assets/img/parigi/louvre.jpg", "descrizione": "Noto museo con opere d'arte inestimabili", "rating": 5, "votanti": "192.789"},
  {"id":9, "monumentName": "Cattedrale di Nortre-Dame", "img": "assets/img/parigi/notredame.jpg", "descrizione": "Famosa chiesa in stile gotico", "rating": 4, "votanti": "42.029"},
  {"id":10, "monumentName": "Arco di trionfo", "img": "assets/img/parigi/trionfo.jpg", "descrizione": "Arco di trionfo e monumento nazionale", "rating": 4, "votanti": "134.251"},
  {"id":11, "monumentName": "Avenue des Champs-Elysees", "img": "assets/img/parigi/elysees.jpg", "descrizione": "Monumento nazionale", "rating": 4, "votanti": "63.186"},
  {"id":12, "monumentName": "Moulin Rouge", "img": "assets/img/parigi/rouge.jpg", "descrizione": "Famoso cabaret belle epoque", "rating": 4, "votanti": "7.309"}
]

export const itemsLondra: any[] = [
  {"id":13, "monumentName": "Big Ben", "img": "assets/img/londra/bigben.jpg", "descrizione": "Torre simbolo di Londra", "rating": 4, "votanti": "41.595"},
  {"id":14, "monumentName": "London Eye", "img": "assets/img/londra/londoneye.jpg", "descrizione": "Celebre ruota panoramica sul fiume", "rating": 5, "votanti": "118.751"},
  {"id":15, "monumentName": "Torre di Londra", "img": "assets/img/londra/torrelondra.jpeg", "descrizione": "Fortezza con i gioielli della corona", "rating": 5, "votanti": "69.875"},
  {"id":16, "monumentName": "Tower Bridge", "img": "assets/img/londra/bridge.jpg", "descrizione": "Ponte sul fiume", "rating": 5, "votanti": "100.534"},
  {"id":17, "monumentName": "Buckingham Palace", "img": "assets/img/londra/palace.jpg", "descrizione": "Residenza della regina", "rating": 5, "votanti": "129.798"},
  {"id":18, "monumentName": "British Museum", "img": "assets/img/londra/museumbritish.jpg", "descrizione": "Museo con reperti storici inestimabili", "rating": 5, "votanti": "103.643"}
]

export const itemsMadrid: any[] = [
  {"id":19, "monumentName": "Palazzo reale di Madrid", "img": "assets/img/madrid/reale.jpg", "descrizione": "Palazzo reale con 2000 sale e il parco", "rating": 5, "votanti": "41.895"},
  {"id":20, "monumentName": "Plaza Mayor", "img": "assets/img/madrid/mayor.jpg", "descrizione": "Vivace piazza principale di Madrid", "rating": 5, "votanti": "106.327"},
  {"id":21, "monumentName": "Museo del Prado", "img": "assets/img/madrid/prado.jpg", "descrizione": "Rinomata collezuione d'arte europea", "rating": 5, "votanti": "69.765"},
  {"id":22, "monumentName": "Parco del Retiro", "img": "assets/img/madrid/retiro.jpg", "descrizione": "Grande parco del XIX secolo con fontane", "rating": 5, "votanti": "110.352"},
  {"id":23, "monumentName": "Puerta del Sol", "img": "assets/img/madrid/sol.jpg", "descrizione": "Monumento storico con orologio", "rating": 4, "votanti": "71.435"},
  {"id":24, "monumentName": "Mercato di San Miguel", "img": "assets/img/madrid/miguel.jpg", "descrizione": "Elegante mercato gastronomico coperto", "rating": 4, "votanti": "72.734"}
]

export const infoRome: any = {city: 'Roma, Italia', flag: 'italy.png'};
export const infoParigi: any = {city: 'Parigi, Francia', flag: 'francia.png'};
export const infoLondra: any = {city: 'Londra, Regno Unito', flag: 'england.png'};
export const infoMadrid: any = {city: 'Madrid, Spagna', flag: 'spain.png'};

export const details: any[] = [
  {"id": 1, "city":"Roma", "monumentName": "Colosseo", "img": "assets/img/rome/colosseo.jpg", "descrizione": "Il Colosseo, originariamente conosciuto come Amphitheatrum Flavium (in italiano: Anfiteatro Flavio) o semplicemente come Amphitheatrum, è il più grande anfiteatro del mondo, situato nel centro della città di Roma. In grado di contenere un numero di spettatori stimato tra 50.000 e 87.000 unità, è il più importante anfiteatro romano, nonché il più imponente monumento dell'antica Roma che sia giunto fino a noi, conosciuto in tutto il mondo come simbolo della città di Roma e uno dei simboli d'Italia.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Colosseo"},
  {"id": 2, "city":"Roma", "monumentName": "Basilica di San Pietro", "img": "assets/img/rome/vaticano.jpg", "descrizione": "La basilica di San Pietro in Vaticano, ufficialmente papale arcibasilica maggiore di San Pietro in Vaticano, è una basilica cattolica della Città del Vaticano; simbolo dello Stato del Vaticano, cui fa da coronamento la monumentale piazza San Pietro. È la più grande delle quattro basiliche papali di Roma, spesso descritta come la più grande chiesa del mondo e centro del cattolicesimo. Non è tuttavia la chiesa cattedrale della diocesi romana poiché tale titolo spetta alla basilica di San Giovanni in Laterano, che è anche la prima per dignità essendo Madre e Capo di tutte le Chiese dell'Urbe e del Mondo.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Basilica_di_San_Pietro_in_Vaticano"},
  {"id": 3, "city":"Roma", "monumentName": "Fori Imperiali", "img": "assets/img/rome/fori.jpg", "descrizione": "I Fori Imperiali costituiscono una serie di cinque piazze monumentali edificate nel corso di un secolo e mezzo (tra il 46 a.C. e il 113 d.C.) nel cuore della città di Roma da parte degli imperatori. Di essi non fa invece parte il Foro Romano, ossia la vecchia piazza repubblicana, la cui prima sistemazione risale all'età regia (VI secolo a.C.) e che era stato per secoli il centro politico, religioso ed economico della città, ma che non ebbe mai un carattere unitario. Sotto Cesare e Augusto, la costruzione della Basilica Giulia e il rifacimento della Basilica Emilia, che delimitavano i lati lunghi della piazza, diedero tuttavia al Foro una certa regolarità.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Fori_Imperiali"},
  {"id": 4, "city":"Roma", "monumentName": "Fontana di Trevi", "img": "assets/img/rome/trevi.png", "descrizione": "La Fontana di Trevi è la più grande e una fra le più celebri fontane di Roma. Fu costruita sulla facciata di Palazzo Poli (più propriamente detto Palazzo Conti di Poli), da Nicola Salvi. Il concorso indetto da papa Clemente XII nel 1731 era stato vinto dallo scultore francese Lambert-Sigisbert Adam, ma successivamente l'incarico passò a Salvi (si dice che il papa non voleva affidare l'opera a uno straniero, ma un'altra versione spiega che Adam doveva ritornare in Francia) che la incominciò nel 1732. Fu completata nel 1762 da Giuseppe Pannini e stilisticamente appartiene al tardo barocco. La fontana è stata costruita con travertino, marmo, intonaco, stucco e metalli.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Fontana_di_Trevi"},
  {"id": 5, "city":"Roma", "monumentName": "Pantheon", "img": "assets/img/rome/pantheon.jpeg", "descrizione": "Il Pantheon (in greco antico: Πάνθεον [ἱερόν], Pántheon [hierón], «[tempio] di tutti gli dei»), in latino classico Pantheum, è un edificio della Roma antica situato nel rione Pigna nel centro storico, costruito come tempio dedicato a tutte le divinità passate, presenti e future. Fu fondato nel 27 a.C. dall'arpinate Marco Vipsanio Agrippa, genero di Augusto. Fu fatto ricostruire dall'imperatore Adriano tra il 120 e il 124 d.C., dopo che gli incendi dell'80 e del 110 d.C. avevano danneggiato la costruzione precedente di età augustea.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Pantheon_(Roma)"},
  {"id": 6, "city":"Roma", "monumentName": "Altare della Patria", "img": "assets/img/rome/patria.jpg", "descrizione": "Il Monumento nazionale a Vittorio Emanuele II o (Mole del) Vittoriano, impropriamente detto Altare della Patria, è un complesso monumentale nazionale italiano situato a Roma in piazza Venezia, sul versante settentrionale del colle del Campidoglio, opera degli architetti Ettore Ferrari e Pio Piacentini, che idearono il progetto di massima, e Giuseppe Sacconi, che fu l'artefice del progetto di dettaglio. Fu costruito a partire dal 1885, con i lavori che si conclusero nel 1935: tuttavia l'inaugurazione ufficiale e la contestuale apertura al pubblico erano avvenute già nel 1911, in occasione degli eventi collegati all'Esposizione internazionale di Torino, durante le celebrazioni del 50º anniversario dell'Unità d'Italia. Da un punto di vista architettonico è stato pensato come un moderno foro, un'agorà su tre livelli collegati da scalinate e sovrastato da un portico caratterizzato da un colonnato.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Vittoriano"},
  {"id": 7, "city":"Parigi", "monumentName": "Torre Eiffel", "img": "assets/img/parigi/eiffel.jpg", "descrizione": "La torre Eiffel si trova nella parte occidentale VII arrondissement, nel pieno centro di Parigi, all'estremità nord-occidentale dello Champ de Mars. La struttura è eretta su un piano a 33,50 metri sul livello del mare, non lontano dalle rive della Senna, dove sono dislocati pontili destinati all'ormeggio di imbarcazioni da diporto. Tutt'intorno alla torre si ergono edifici di grande interesse storico e architettonico, come l'École Militaire, il Pont d'Iéna, il Palais de Chaillot e la sede dell'UNESCO.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Torre_Eiffel"},
  {"id": 8, "city":"Parigi", "monumentName": "Museo del Louvre", "img": "assets/img/parigi/louvre.jpg", "descrizione": "Il museo ha preso il nome dal palazzo che lo ospita. Originariamente era una fortezza, costruita alla fine del XII secolo durante il regno del re capetingio Filippo II, nei rifacimenti successivi fu sede reale e governativa. La conformazione attuale del palazzo origina dai lavori ordinati da Carlo V di Francia nella seconda metà del XIV secolo. Fu la sede effettiva della monarchia francese fino al 1682, quando Luigi XIV si trasferì nella Reggia di Versailles, e rimase comunque la sua sede formale fino al termine dell'Ancien Régime nel 1789. Fu il governo rivoluzionario a dare piena attuazione a progetti già avviati di trasformazione in museo, inaugurandolo come tale nel 1793, anche se il palazzo continuò ad ospitare enti governativi fino agli anni novanta.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Museo_del_Louvre"},
  {"id": 9, "city":"Parigi", "monumentName": "Cattedrale di Nortre-Dame", "img": "assets/img/parigi/notredame.jpg", "descrizione": "La cattedrale metropolitana di Notre-Dame («Nostra Signora»; in francese cathédrale métropolitaine Notre-Dame, pronuncia [nɔtʁə dam]), è il principale luogo di culto cattolico di Parigi, chiesa madre dell'arcidiocesi di Parigi. Ubicata nella parte orientale dell'Île de la Cité, nel cuore della capitale francese, nella piazza omonima, rappresenta una delle costruzioni gotiche più celebri del mondo ed è uno dei monumenti più visitati di Parigi. In base alla Legge francese sulla separazione tra Stato e Chiesa del 1905, l'edificio è proprietà dello Stato francese, come tutte le altre cattedrali fatte costruire dal Regno di Francia, e il suo utilizzo è assegnato alla Chiesa cattolica", "rating": 4, "link":"https://it.wikipedia.org/wiki/Cattedrale_di_Notre-Dame"},
  {"id": 10, "city":"Parigi", "monumentName": "Arco di trionfo", "img": "assets/img/parigi/trionfo.jpg", "descrizione": "L'Arco di Trionfo di Parigi (noto in Francia come Arc de triomphe de l'Étoile) è un importante monumento di Parigi. Si trova alla fine del viale dei Champs-Élysées, al centro della Place de l'Étoile (oggi chiamata Place Charles de Gaulle). Il monumento fu voluto da Napoleone Bonaparte per celebrare la vittoria nella battaglia di Austerlitz.", "rating": 4, "link":"https://it.wikipedia.org/wiki/Arco_di_Trionfo_(Parigi)"},
  {"id": 11, "city":"Parigi", "monumentName": "Avenue des Champs-Elysees", "img": "assets/img/parigi/elysees.jpg", "descrizione": "Il viale, prosecuzione della Rue de Rivoli, corre per 1914 metri attraverso l'VIII arrondissement, nella parte nord-occidentale di Parigi, da Place de la Concorde a est, con il suo obelisco, a Place Charles de Gaulle (già Place de l'Étoile) a ovest, dove si trova l'Arco di trionfo, formando parte della linea dell'Asse storico. Una delle principali destinazioni turistiche di Parigi (vi ha sede il cabaret Lido), la parte bassa degli Champs-Élysées è contornata da spazi verdi (Place Marigny) e da edifici come il Teatro Marigny e il Palais de la découverte. Risalendolo, vi si trovano allineati cinema, teatri, café e ristoranti molto importanti come il Fouquet's, centri commerciali e negozi di lusso. Anche un hotel a 5 stelle rinnovato.", "rating": 4, "link":"https://it.wikipedia.org/wiki/Avenue_des_Champs-%C3%89lys%C3%A9es"},
  {"id": 12, "city":"Parigi", "monumentName": "Moulin Rouge", "img": "assets/img/parigi/rouge.jpg", "descrizione": "Il Moulin Rouge (in italiano, letteralmente 'Mulino Rosso'), situato nel famoso quartiere a luci rosse di Pigalle, al XVIII arrondissement di Parigi, vicino a Montmartre è uno dei più famosi locali di Parigi, inaugurato il 6 ottobre 1891 da Charles Zidler e da Joseph Oller. La sede originale del teatro, che bruciò nel 1915, era stata co-fondata nel 1889 da Charles Zidler e da Joseph Oller (quest'ultimo era anche proprietario dell'Olympia di Parigi). Posto nei pressi di Montmartre nel quartiere di Pigalle, su Boulevard de Clichy, il locale divenne particolarmente famoso per la presenza di un mulino a vento di colore rosso sul tetto della struttura, che appunto diede il nome al locale.", "rating": 4, "link":"https://it.wikipedia.org/wiki/Moulin_Rouge"},
  {"id": 13, "city":"Londra", "monumentName": "Big Ben", "img": "assets/img/londra/bigben.jpg", "descrizione": "Big Ben è il soprannome della campana più grande della torre dell'orologio del palazzo di Westminster, a Londra. Per tradizione l'uso del nome si è esteso anche all'orologio e all'intera torre in stile neogotico, alta 96 m, la cui edificazione iniziò nel 1834 e si concluse nel 1858. Conosciuta come Clock Tower (Torre dell'Orologio), il nome fu cambiato ufficialmente in Elizabeth Tower, in occasione del Giubileo di diamante di Elisabetta II del giugno 2012. Questa torre campanaria suona ogni quarto d'ora.", "rating": 4, "link":"https://it.wikipedia.org/wiki/Big_Ben"},
  {"id": 14, "city":"Londra", "monumentName": "London Eye", "img": "assets/img/londra/londoneye.jpg", "descrizione": "Il London Eye (in italiano occhio di Londra), anche noto come Millennium Wheel (in italiano Ruota del Millennio), è una ruota panoramica situata sulla riva sud del Tamigi tra il Ponte di Westminster e l'Hungerford Bridge, a Londra. Il suo nome ufficiale era originariamente British Airways London Eye, poi Merlin Entertainments London Eye, EDF Energy London Eye e Coca-Cola London Eye dal gennaio 2015 a seguito della sponsorizzata da parte di Coca-Cola[", "rating": 5, "link":"https://it.wikipedia.org/wiki/London_Eye"},
  {"id": 15, "city":"Londra", "monumentName": "Torre di Londra", "img": "assets/img/londra/torrelondra.jpeg", "descrizione": "La Torre di Londra (Tower of London) è un castello situato nel centro di Londra, sulla riva nord del Tamigi. Si trova all'interno del London Borough of Tower Hamlets, separato dal margine orientale della città di Londra da uno spazio aperto conosciuto come Tower Hill. Fu costruita a partire dalla fine del 1066 come parte della conquista normanna dell'Inghilterra. La Torre Bianca, che conferisce all'intero castello il nome, fu edificata da Guglielmo il Conquistatore nel 1078, ed è stata un simbolo di risentita oppressione inflitta a Londra dai nuovi sovrani. Il castello è stato utilizzato, a partire dal 1100, come prigione (Rainulfo Flambard fu il primo a esservi imprigionato) fino al 1952 con la detenzione dei gemelli Kray, anche se questo non fu mai il suo scopo principale.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Torre_di_Londra"},
  {"id": 16, "city":"Londra", "monumentName": "Tower Bridge", "img": "assets/img/londra/bridge.jpg", "descrizione": "Il Tower Bridge è un ponte relativamente recente, poiché la sua costruzione iniziò nel 1886 e fu completata nel 1894. A partire dalla seconda metà del XX secolo il Tower Bridge ha cominciato a riscuotere un successo internazionale, diventando uno dei principali simboli di Londra, preceduto soltanto dal Big Ben e affiancato da Trafalgar Square e dal London Eye. Proprio per la sua notorietà, spesso nel linguaggio comune si tende a confonderlo con il vicino London Bridge, che invece è un ponte a sé stante posto a monte e sebbene le due strutture abbiano storie e architettura decisamente differenti.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Tower_Bridge"},
  {"id": 17, "city":"Londra", "monumentName": "Buckingham Palace", "img": "assets/img/londra/palace.jpg", "descrizione": "Buckingham Palace, situato nella Città di Westminster a Londra, è la residenza ufficiale della sovrana del Regno Unito. L'espressione Buckingham Palace o semplicemente The Palace è diventata comune per esprimere tutto ciò che riguarda gli ambienti della Corte e della famiglia reale. Oltre ad essere la residenza ufficiale della Regina, Buckingham Palace è il luogo in cui si svolgono numerose cerimonie pubbliche (dai ricevimenti dei reali alle visite dei vari capi di Stato) ed è anche una notevole attrazione turistica (famoso in tutto il mondo è il cambio della Guardia). Da un punto di vista più profondo, ha sempre rappresentato un punto di riferimento per i sudditi, nei momenti gioiosi e tristi della storia del Regno Unito. Il palazzo si estende su una superficie di 77.000 m²", "rating": 5, "link":"https://it.wikipedia.org/wiki/Buckingham_Palace"},
  {"id": 18, "city":"Londra", "monumentName": "British Museum", "img": "assets/img/londra/museumbritish.jpg", "descrizione": "Il British Museum (in italiano: Museo Britannico) è uno dei più grandi e importanti musei della storia del mondo. È stato fondato nel 1753 da Sir Hans Sloane, un medico e scienziato che ha collezionato un patrimonio letterario e artistico nel suo nucleo originario: la biblioteca di Montague House a Londra, in seguito acquistata dallo Stato britannico per ventimila sterline e aperta al pubblico il 15 gennaio 1759. L'attuale presidente è Sir John Boyd. Il museo ospita circa 8 milioni di oggetti che testimoniano la storia e la cultura materiale dell'umanità dalle origini alla contemporaneità. Si trova a Great Russell Street, nella città di Londra.", "rating": 5, "link":"https://it.wikipedia.org/wiki/British_Museum"},
  {"id": 19, "city":"Madrid", "monumentName": "Palazzo reale di Madrid", "img": "assets/img/madrid/reale.jpg", "descrizione": "Il Palazzo reale di Madrid, anche chiamato Palazzo d’Oriente, riprendendo il nome della piazza sulla quale si affaccia ad est (un paradosso, perché il palazzo si trova nella zona più occidentale della città), è stata ed è ancora oggi la residenza ufficiale della famiglia reale spagnola. Oggi il palazzo è utilizzato esclusivamente per le cerimonie, le conferenze e gli atti ufficiali, dato che i monarchi vivono nel Palazzo della Zarzuela, situato alla periferia di Madrid. Il palazzo fu costruito nello stesso luogo dove sorgeva l'Alcázar, fortezza musulmana del IX secolo edificata su ordine dell'emiro Mohamed I per difendersi dall'avanzata dei cristiani, divenuta nel XVI secolo palazzo reale dopo la decisione di stabilire a Madrid la capitale dell'Impero spagnolo; fu residenza della famiglia reale spagnola fino alla sua distruzione causata da un terribile incendio avvenuto la vigilia di Natale del 1734, ai tempi di Filippo V.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Palazzo_reale_di_Madrid"},
  {"id": 20, "city":"Madrid", "monumentName": "Plaza Mayor", "img": "assets/img/madrid/mayor.jpg", "descrizione": "La Plaza Mayor de Madrid è situata al centro della città, a pochi metri dalla piazza della Puerta del Sol e dalla Plaza de la Villa insieme alla calle Mayor.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Plaza_Mayor_(Madrid)"},
  {"id": 21, "city":"Madrid", "monumentName": "Museo del Prado", "img": "assets/img/madrid/prado.jpg", "descrizione": "Il Museo del Prado è una delle pinacoteche più importanti del mondo e si trova a Madrid in Spagna. Vi sono esposte opere dei maggiori artisti italiani, spagnoli e fiamminghi, fra cui Beato Angelico, Andrea Mantegna, Raffaello Sanzio, Hieronymus Bosch, Rogier van der Weyden, Bruegel il Vecchio, El Greco, Pieter Paul Rubens, Tiziano, Diego Velázquez, Francisco Goya.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Museo_del_Prado"},
  {"id": 22, "city":"Madrid", "monumentName": "Parco del Retiro", "img": "assets/img/madrid/retiro.jpg", "descrizione": "Il parco del Retiro (da non confondersi con i giardini del Buon Ritiro) è un parco di Madrid che si estende per 118 ettari e rappresenta uno dei principali luoghi di interesse della capitale spagnola.", "rating": 5, "link":"https://it.wikipedia.org/wiki/Parco_del_Retiro"},
  {"id": 23, "city":"Madrid", "monumentName": "Puerta del Sol", "img": "assets/img/madrid/sol.jpg", "descrizione": "La Puerta del Sol è una delle piazze più importanti e famose di Madrid. Essa rappresenta il km 0 della rete stradale della Spagna ed è il centro delle celebrazioni nazionali della mezzanotte di San Silvestro con il famoso orologio che batte i 12 rintocchi (le campanadas). La Statua dell'Orso e del Corbezzolo Puerta del Sol a Madrid durante le proteste di Spagna 2011. È inoltre situata vicino alla Plaza Mayor.", "rating": 4, "link":"https://it.wikipedia.org/wiki/Puerta_del_Sol"},
  {"id": 24, "city":"Madrid", "monumentName": "Mercato di San Miguel", "img": "assets/img/madrid/miguel.jpg", "descrizione": "Il mercato di San Miguel (in spagnolo: Mercado de San Micuel) è un mercato coperto situato a Madrid, in Spagna. Originariamente costruito nel 1916, è stato acquistato da investitori privati ​​nel 2003 che hanno rinnovato la struttura in ferro e riaperta nel 2009.", "rating": 4, "link":"https://en.wikipedia.org/wiki/Market_of_San_Miguel"},
]
